=== stamacake/JSON_serialization/src/main/resources/bsa999.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="task" type="task" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="team" type="team" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="student" type="student" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="task">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="value">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minExclusive value="0"/>
						<xs:maxExclusive value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="team">
		<xs:sequence>
			<xs:element name="tasksList">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="task" type="task" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="student">
		<xs:sequence>
			<xs:element name="first_name" type="xs:string"/>
			<xs:element name="second_name" type="xs:string"/>
			<xs:element name="age" type="xs:integer"/>
			<xs:element name="team" type="team"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== stamacake/JSON_serialization/src/main/resources/rootXml.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bsa999.xsd">
		<task>
			<id>RSC781</id>
			<name>Bugfixing</name>
			<value>6</value>
		</task>
		<task>
			<id>RSA999</id>
			<name>Creating</name>
			<value>1</value>
		</task>
		<team>
    <tasksList>
        <task>
            <id>IJK9288</id>
            <name>Add New Feature</name>
            <value>3</value>
        </task>
        <task>
            <id>TYE9273</id>
            <name>Bugfixing</name>
            <value>4</value>
        </task>
    </tasksList>
    <name>team1</name>
</team>
		<student>
			<first_name>Vasya</first_name>
			<second_name>Pupkin</second_name>
			<age>19</age>
			<team>
				<tasksList>
					<task>
						<id>virtual</id>
						<name>Virtualization</name>
						<value>6</value>
					</task>
					<task>
						<id>Js</id>
						<name>Json Serialization</name>
						<value>5</value>
					</task>
				</tasksList>
			<name>team1</name>
		</team>
	</student>
</root>
